name: Release package
on:
  push:
    tags:
      - '*'
jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    name: 'Build Docker Image'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest
      - name: Build Docker image - prod
        run: |
          docker buildx build \
            --target prod \
            --load \
            -t report:prod \
            -f ./tools/Dockerfile \
            .
          docker save report:prod | gzip > report-prod.tar.gz
