name: Test

on:
  - push

jobs:

  yml-lint:
    runs-on: ubuntu-latest
    name: 'YML lint'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v5
      - run: docker pull cytopia/yamllint
      - run: docker run --rm -t -v $(pwd):/data cytopia/yamllint --config-file=tests/.yamllint .

  markdown-lint:
    runs-on: ubuntu-latest
    name: 'Markdown lint'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v5
      - run: docker pull tmknom/markdownlint
      - run: docker run --rm -v $(pwd):/work tmknom/markdownlint '**/*.md' --config tests/.markdownlintrc --ignore CHANGELOG.md --ignore .venv

  build-docker-image:
    runs-on: ubuntu-latest
    name: 'Build Docker Image'
    timeout-minutes: 20
    needs:
      - yml-lint
      - markdown-lint
    steps:
      - uses: actions/checkout@v5
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest
      - name: Build Docker image - test
        run: |
          docker buildx build \
            --target test \
            --cache-from type=gha,scope=test \
            --cache-to type=gha,mode=max,scope=test \
            --load \
            -t report:test \
            -f ./tools/Dockerfile \
            .
          docker save report:test | gzip > report-test.tar.gz
      - uses: actions/upload-artifact@v6
        with:
          name: docker-image-report-test
          path: report-test.tar.gz
          retention-days: 7

  cs-lint:
    runs-on: ubuntu-latest
    name: 'CS Lint'
    timeout-minutes: 5
    needs:
      - build-docker-image
    steps:
      - uses: actions/checkout@v5
      - run: mkdir -p /tmp/docker
      - uses: actions/download-artifact@v8
        with:
          name: docker-image-report-test
          path: /tmp/docker
      - name: CS Lint
        run: |
          docker load < /tmp/docker/report-test.tar.gz
          docker run --user worker report:test sh -c "uv run -m ruff check && uv run -m ruff format --check"
